plugins {
    id 'java'
    id 'fabric-loom' version '1.14-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

def libbulletVariants = [
        "Linux64",
        "Linux_ARM32hf",
        "Linux_ARM64",
        "MacOSX64",
        "MacOSX_ARM64",
        "Windows64"
]

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven { url "https://maven.tomalbrc.de" }
    maven { url 'https://maven.nucleoid.xyz' }
    maven { url 'https://maven.blamejared.com' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modImplementation ("eu.pb4:polymer-core:${project.polymer_version}")
    modImplementation ("eu.pb4:polymer-blocks:${project.polymer_version}")
    modImplementation ("eu.pb4:polymer-resource-pack:${project.polymer_version}")
    modImplementation ("eu.pb4:polymer-resource-pack-extras:${project.polymer_version}")
    modImplementation ("eu.pb4:polymer-virtual-entity:${project.polymer_version}")
    modImplementation ("eu.pb4:polymer-networking:${project.polymer_version}")
    modImplementation ("eu.pb4:polymer-autohost:${project.polymer_version}")
    modImplementation ("eu.pb4:polymer-sound-patcher:${project.polymer_version}")
    modImplementation include("eu.pb4:sgui:${project.sgui_version}")
    modImplementation include('me.lucko:fabric-permissions-api:0.6.1')

    implementation include("io.github.electrostat-lab:snaploader:1.0.0-stable")
    libbulletVariants.each { variant ->
        implementation("com.github.stephengold:jolt-jni-${variant}:3.5.1")
        runtimeOnly("com.github.stephengold:jolt-jni-${variant}:3.5.1:ReleaseDp")

        //implementation include("com.github.stephengold:Libbulletjme-${variant}:22.0.3")
        //runtimeOnly("com.github.stephengold:Libbulletjme-${variant}:22.0.3:SpRelease")
    }

    testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'

    testImplementation 'com.github.noconnor:junitperf-junit5:1.37.0'
    testRuntimeOnly 'com.github.noconnor:junitperf-junit5:1.37.0'
}


test {
    useJUnitPlatform()
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    repositories {

    }
}
